INSTRUCTION_SETS = {
    "rv_i": {
        "add": ['rd', 'rs1', 'rs2'],
        "addi": ['rd', 'rs1', 'imm12'],
        "and": ['rd', 'rs1', 'rs2'],
        "andi": ['rd', 'rs1', 'imm12'],
        "auipc": ['rd', 'imm20'],
        "beq": ['bimm12hi', 'rs1', 'rs2', 'bimm12lo'],
        "bge": ['bimm12hi', 'rs1', 'rs2', 'bimm12lo'],
        "bgeu": ['bimm12hi', 'rs1', 'rs2', 'bimm12lo'],
        "blt": ['bimm12hi', 'rs1', 'rs2', 'bimm12lo'],
        "bltu": ['bimm12hi', 'rs1', 'rs2', 'bimm12lo'],
        "bne": ['bimm12hi', 'rs1', 'rs2', 'bimm12lo'],
        "ebreak": [],
        "ecall": [],
        "fence": ['fm', 'pred', 'succ', 'rs1', 'rd'],
        "fence.tso": ['rs1', 'rd'],
        "jal": ['rd', 'jimm20'],
        "jalr": ['rd', 'rs1', 'imm12'],
        "lb": ['rd', 'rs1', 'imm12'],
        "lbu": ['rd', 'rs1', 'imm12'],
        "lh": ['rd', 'rs1', 'imm12'],
        "lhu": ['rd', 'rs1', 'imm12'],
        "lui": ['rd', 'imm20'],
        "lw": ['rd', 'rs1', 'imm12'],
        "or": ['rd', 'rs1', 'rs2'],
        "ori": ['rd', 'rs1', 'imm12'],
        "pause": [],
        "sb": ['imm12hi', 'rs1', 'rs2', 'imm12lo'],
        "sbreak": [],
        "scall": [],
        "sh": ['imm12hi', 'rs1', 'rs2', 'imm12lo'],
        "sll": ['rd', 'rs1', 'rs2'],
        "slt": ['rd', 'rs1', 'rs2'],
        "slti": ['rd', 'rs1', 'imm12'],
        "sltiu": ['rd', 'rs1', 'imm12'],
        "sltu": ['rd', 'rs1', 'rs2'],
        "sra": ['rd', 'rs1', 'rs2'],
        "srl": ['rd', 'rs1', 'rs2'],
        "sub": ['rd', 'rs1', 'rs2'],
        "sw": ['imm12hi', 'rs1', 'rs2', 'imm12lo'],
        "xor": ['rd', 'rs1', 'rs2'],
        "xori": ['rd', 'rs1', 'imm12'],
        "li": ['rd', 'imm40'],# gzh Uncertain about the bit-width of the immediate value
        "nop": [],#
    },
    "rv_zpn": {
        "add16": ['rs2', 'rs1', 'rd'],
        "add8": ['rs2', 'rs1', 'rd'],
        "ave": ['rs2', 'rs1', 'rd'],
        "clrov": ['rd'],
        "clrs16": ['rs1', 'rd'],
        "clrs32": ['rs1', 'rd'],
        "clrs8": ['rs1', 'rd'],
        "clz16": ['rs1', 'rd'],
        "clz32": ['rs1', 'rd'],
        "clz8": ['rs1', 'rd'],
        "cmpeq16": ['rs2', 'rs1', 'rd'],
        "cmpeq8": ['rs2', 'rs1', 'rd'],
        "cras16": ['rs2', 'rs1', 'rd'],
        "crsa16": ['rs2', 'rs1', 'rd'],
        "kabs16": ['rs1', 'rd'],
        "kabs8": ['rs1', 'rd'],
        "kabsw": ['rs1', 'rd'],
        "kadd16": ['rs2', 'rs1', 'rd'],
        "kadd8": ['rs2', 'rs1', 'rd'],
        "kaddh": ['rs2', 'rs1', 'rd'],
        "kaddw": ['rs2', 'rs1', 'rd'],
        "kcras16": ['rs2', 'rs1', 'rd'],
        "kcrsa16": ['rs2', 'rs1', 'rd'],
        "kdmabb": ['rs2', 'rs1', 'rd'],
        "kdmabt": ['rs2', 'rs1', 'rd'],
        "kdmatt": ['rs2', 'rs1', 'rd'],
        "kdmbb": ['rs2', 'rs1', 'rd'],
        "kdmbt": ['rs2', 'rs1', 'rd'],
        "kdmtt": ['rs2', 'rs1', 'rd'],
        "khm16": ['rs2', 'rs1', 'rd'],
        "khm8": ['rs2', 'rs1', 'rd'],
        "khmbb": ['rs2', 'rs1', 'rd'],
        "khmbt": ['rs2', 'rs1', 'rd'],
        "khmtt": ['rs2', 'rs1', 'rd'],
        "khmx16": ['rs2', 'rs1', 'rd'],
        "khmx8": ['rs2', 'rs1', 'rd'],
        "kmabb": ['rs2', 'rs1', 'rd'],
        "kmabt": ['rs2', 'rs1', 'rd'],
        "kmada": ['rs2', 'rs1', 'rd'],
        "kmadrs": ['rs2', 'rs1', 'rd'],
        "kmads": ['rs2', 'rs1', 'rd'],
        "kmatt": ['rs2', 'rs1', 'rd'],
        "kmaxda": ['rs2', 'rs1', 'rd'],
        "kmaxds": ['rs2', 'rs1', 'rd'],
        "kmda": ['rs2', 'rs1', 'rd'],
        "kmmac": ['rs2', 'rs1', 'rd'],
        "kmmac.u": ['rs2', 'rs1', 'rd'],
        "kmmawb": ['rs2', 'rs1', 'rd'],
        "kmmawb2": ['rs2', 'rs1', 'rd'],
        "kmmawb2.u": ['rs2', 'rs1', 'rd'],
        "kmmawb.u": ['rs2', 'rs1', 'rd'],
        "kmmawt": ['rs2', 'rs1', 'rd'],
        "kmmawt2": ['rs2', 'rs1', 'rd'],
        "kmmawt2.u": ['rs2', 'rs1', 'rd'],
        "kmmawt.u": ['rs2', 'rs1', 'rd'],
        "kmmsb": ['rs2', 'rs1', 'rd'],
        "kmmsb.u": ['rs2', 'rs1', 'rd'],
        "kmmwb2": ['rs2', 'rs1', 'rd'],
        "kmmwb2.u": ['rs2', 'rs1', 'rd'],
        "kmmwt2": ['rs2', 'rs1', 'rd'],
        "kmmwt2.u": ['rs2', 'rs1', 'rd'],
        "kmsda": ['rs2', 'rs1', 'rd'],
        "kmsxda": ['rs2', 'rs1', 'rd'],
        "kmxda": ['rs2', 'rs1', 'rd'],
        "ksll16": ['rs2', 'rs1', 'rd'],
        "ksll8": ['rs2', 'rs1', 'rd'],
        "kslli16": ['imm4', 'rs1', 'rd'],
        "kslli8": ['imm3', 'rs1', 'rd'],
        "kslliw": ['imm5', 'rs1', 'rd'],
        "ksllw": ['rs2', 'rs1', 'rd'],
        "kslra16": ['rs2', 'rs1', 'rd'],
        "kslra16.u": ['rs2', 'rs1', 'rd'],
        "kslra8": ['rs2', 'rs1', 'rd'],
        "kslra8.u": ['rs2', 'rs1', 'rd'],
        "kslraw": ['rs2', 'rs1', 'rd'],
        "kslraw.u": ['rs2', 'rs1', 'rd'],
        "kstas16": ['rs2', 'rs1', 'rd'],
        "kstsa16": ['rs2', 'rs1', 'rd'],
        "ksub16": ['rs2', 'rs1', 'rd'],
        "ksub8": ['rs2', 'rs1', 'rd'],
        "ksubh": ['rs2', 'rs1', 'rd'],
        "ksubw": ['rs2', 'rs1', 'rd'],
        "kwmmul": ['rs2', 'rs1', 'rd'],
        "kwmmul.u": ['rs2', 'rs1', 'rd'],
        "maddr32": ['rs2', 'rs1', 'rd'],
        "msubr32": ['rs2', 'rs1', 'rd'],
        "pbsad": ['rs2', 'rs1', 'rd'],
        "pbsada": ['rs2', 'rs1', 'rd'],
        "pkbt16": ['rs2', 'rs1', 'rd'],
        "pktb16": ['rs2', 'rs1', 'rd'],
        "radd16": ['rs2', 'rs1', 'rd'],
        "radd8": ['rs2', 'rs1', 'rd'],
        "raddw": ['rs2', 'rs1', 'rd'],
        "rcras16": ['rs2', 'rs1', 'rd'],
        "rcrsa16": ['rs2', 'rs1', 'rd'],
        "rdov": ['rd'],
        "rstas16": ['rs2', 'rs1', 'rd'],
        "rstsa16": ['rs2', 'rs1', 'rd'],
        "rsub16": ['rs2', 'rs1', 'rd'],
        "rsub8": ['rs2', 'rs1', 'rd'],
        "rsubw": ['rs2', 'rs1', 'rd'],
        "sclip16": ['imm4', 'rs1', 'rd'],
        "sclip32": ['imm5', 'rs1', 'rd'],
        "sclip8": ['imm3', 'rs1', 'rd'],
        "scmple16": ['rs2', 'rs1', 'rd'],
        "scmple8": ['rs2', 'rs1', 'rd'],
        "scmplt16": ['rs2', 'rs1', 'rd'],
        "scmplt8": ['rs2', 'rs1', 'rd'],
        "sll16": ['rs2', 'rs1', 'rd'],
        "sll8": ['rs2', 'rs1', 'rd'],
        "slli16": ['imm4', 'rs1', 'rd'],
        "slli8": ['imm3', 'rs1', 'rd'],
        "smaqa": ['rs2', 'rs1', 'rd'],
        "smaqa.su": ['rs2', 'rs1', 'rd'],
        "smax16": ['rs2', 'rs1', 'rd'],
        "smax8": ['rs2', 'rs1', 'rd'],
        "smbb16": ['rs2', 'rs1', 'rd'],
        "smbt16": ['rs2', 'rs1', 'rd'],
        "smdrs": ['rs2', 'rs1', 'rd'],
        "smds": ['rs2', 'rs1', 'rd'],
        "smin16": ['rs2', 'rs1', 'rd'],
        "smin8": ['rs2', 'rs1', 'rd'],
        "smmul.u": ['rs2', 'rs1', 'rd'],
        "smmwb": ['rs2', 'rs1', 'rd'],
        "smmwb.u": ['rs2', 'rs1', 'rd'],
        "smmwt": ['rs2', 'rs1', 'rd'],
        "smmwt.u": ['rs2', 'rs1', 'rd'],
        "smtt16": ['rs2', 'rs1', 'rd'],
        "smxds": ['rs2', 'rs1', 'rd'],
        "sra16": ['rs2', 'rs1', 'rd'],
        "sra16.u": ['rs2', 'rs1', 'rd'],
        "sra8": ['rs2', 'rs1', 'rd'],
        "sra8.u": ['rs2', 'rs1', 'rd'],
        "sra.u": ['rs2', 'rs1', 'rd'],
        "srai16": ['imm4', 'rs1', 'rd'],
        "srai16.u": ['imm4', 'rs1', 'rd'],
        "srai8": ['imm3', 'rs1', 'rd'],
        "srai8.u": ['imm3', 'rs1', 'rd'],
        "srl16": ['rs2', 'rs1', 'rd'],
        "srl16.u": ['rs2', 'rs1', 'rd'],
        "srl8": ['rs2', 'rs1', 'rd'],
        "srl8.u": ['rs2', 'rs1', 'rd'],
        "srli16": ['imm4', 'rs1', 'rd'],
        "srli16.u": ['imm4', 'rs1', 'rd'],
        "srli8": ['imm3', 'rs1', 'rd'],
        "srli8.u": ['imm3', 'rs1', 'rd'],
        "stas16": ['rs2', 'rs1', 'rd'],
        "stsa16": ['rs2', 'rs1', 'rd'],
        "sub16": ['rs2', 'rs1', 'rd'],
        "sub8": ['rs2', 'rs1', 'rd'],
        "sunpkd810": ['rs1', 'rd'],
        "sunpkd820": ['rs1', 'rd'],
        "sunpkd830": ['rs1', 'rd'],
        "sunpkd831": ['rs1', 'rd'],
        "sunpkd832": ['rs1', 'rd'],
        "uclip16": ['imm4', 'rs1', 'rd'],
        "uclip32": ['imm5', 'rs1', 'rd'],
        "uclip8": ['imm3', 'rs1', 'rd'],
        "ucmple16": ['rs2', 'rs1', 'rd'],
        "ucmple8": ['rs2', 'rs1', 'rd'],
        "ucmplt16": ['rs2', 'rs1', 'rd'],
        "ucmplt8": ['rs2', 'rs1', 'rd'],
        "ukadd16": ['rs2', 'rs1', 'rd'],
        "ukadd8": ['rs2', 'rs1', 'rd'],
        "ukaddh": ['rs2', 'rs1', 'rd'],
        "ukaddw": ['rs2', 'rs1', 'rd'],
        "ukcras16": ['rs2', 'rs1', 'rd'],
        "ukcrsa16": ['rs2', 'rs1', 'rd'],
        "ukstas16": ['rs2', 'rs1', 'rd'],
        "ukstsa16": ['rs2', 'rs1', 'rd'],
        "uksub16": ['rs2', 'rs1', 'rd'],
        "uksub8": ['rs2', 'rs1', 'rd'],
        "uksubh": ['rs2', 'rs1', 'rd'],
        "uksubw": ['rs2', 'rs1', 'rd'],
        "umaqa": ['rs2', 'rs1', 'rd'],
        "umax16": ['rs2', 'rs1', 'rd'],
        "umax8": ['rs2', 'rs1', 'rd'],
        "umin16": ['rs2', 'rs1', 'rd'],
        "umin8": ['rs2', 'rs1', 'rd'],
        "uradd16": ['rs2', 'rs1', 'rd'],
        "uradd8": ['rs2', 'rs1', 'rd'],
        "uraddw": ['rs2', 'rs1', 'rd'],
        "urcras16": ['rs2', 'rs1', 'rd'],
        "urcrsa16": ['rs2', 'rs1', 'rd'],
        "urstas16": ['rs2', 'rs1', 'rd'],
        "urstsa16": ['rs2', 'rs1', 'rd'],
        "ursub16": ['rs2', 'rs1', 'rd'],
        "ursub8": ['rs2', 'rs1', 'rd'],
        "ursubw": ['rs2', 'rs1', 'rd'],
        "zunpkd810": ['rs1', 'rd'],
        "zunpkd820": ['rs1', 'rd'],
        "zunpkd830": ['rs1', 'rd'],
        "zunpkd831": ['rs1', 'rd'],
        "zunpkd832": ['rs1', 'rd'],
    },
    "rv64_zpn": {
        "add32": ['rs2', 'rs1', 'rd'],
        "cras32": ['rs2', 'rs1', 'rd'],
        "crsa32": ['rs2', 'rs1', 'rd'],
        "insb": ['imm3', 'rs1', 'rd'],
        "kabs32": ['rs1', 'rd'],
        "kadd32": ['rs2', 'rs1', 'rd'],
        "kcras32": ['rs2', 'rs1', 'rd'],
        "kcrsa32": ['rs2', 'rs1', 'rd'],
        "kdmabb16": ['rs2', 'rs1', 'rd'],
        "kdmabt16": ['rs2', 'rs1', 'rd'],
        "kdmatt16": ['rs2', 'rs1', 'rd'],
        "kdmbb16": ['rs2', 'rs1', 'rd'],
        "kdmbt16": ['rs2', 'rs1', 'rd'],
        "kdmtt16": ['rs2', 'rs1', 'rd'],
        "khmbb16": ['rs2', 'rs1', 'rd'],
        "khmbt16": ['rs2', 'rs1', 'rd'],
        "khmtt16": ['rs2', 'rs1', 'rd'],
        "kmabb32": ['rs2', 'rs1', 'rd'],
        "kmabt32": ['rs2', 'rs1', 'rd'],
        "kmadrs32": ['rs2', 'rs1', 'rd'],
        "kmads32": ['rs2', 'rs1', 'rd'],
        "kmatt32": ['rs2', 'rs1', 'rd'],
        "kmaxda32": ['rs2', 'rs1', 'rd'],
        "kmaxds32": ['rs2', 'rs1', 'rd'],
        "kmda32": ['rs2', 'rs1', 'rd'],
        "kmsda32": ['rs2', 'rs1', 'rd'],
        "kmsxda32": ['rs2', 'rs1', 'rd'],
        "kmxda32": ['rs2', 'rs1', 'rd'],
        "ksll32": ['rs2', 'rs1', 'rd'],
        "kslli32": ['imm5', 'rs1', 'rd'],
        "kslra32": ['rs2', 'rs1', 'rd'],
        "kslra32.u": ['rs2', 'rs1', 'rd'],
        "kstas32": ['rs2', 'rs1', 'rd'],
        "kstsa32": ['rs2', 'rs1', 'rd'],
        "ksub32": ['rs2', 'rs1', 'rd'],
        "pkbb16": ['rs2', 'rs1', 'rd'],
        "pkbt32": ['rs2', 'rs1', 'rd'],
        "pktb32": ['rs2', 'rs1', 'rd'],
        "pktt16": ['rs2', 'rs1', 'rd'],
        "radd32": ['rs2', 'rs1', 'rd'],
        "rcras32": ['rs2', 'rs1', 'rd'],
        "rcrsa32": ['rs2', 'rs1', 'rd'],
        "rstas32": ['rs2', 'rs1', 'rd'],
        "rstsa32": ['rs2', 'rs1', 'rd'],
        "rsub32": ['rs2', 'rs1', 'rd'],
        "sll32": ['rs2', 'rs1', 'rd'],
        "slli32": ['imm5', 'rs1', 'rd'],
        "smax32": ['rs2', 'rs1', 'rd'],
        "smbt32": ['rs2', 'rs1', 'rd'],
        "smdrs32": ['rs2', 'rs1', 'rd'],
        "smds32": ['rs2', 'rs1', 'rd'],
        "smin32": ['rs2', 'rs1', 'rd'],
        "smmul": ['rs2', 'rs1', 'rd'],
        "smtt32": ['rs2', 'rs1', 'rd'],
        "smxds32": ['rs2', 'rs1', 'rd'],
        "sra32": ['rs2', 'rs1', 'rd'],
        "sra32.u": ['rs2', 'rs1', 'rd'],
        "srai32": ['imm5', 'rs1', 'rd'],
        "srai32.u": ['imm5', 'rs1', 'rd'],
        "srai.u": ['imm6', 'rs1', 'rd'],
        "sraiw.u": ['imm5', 'rs1', 'rd'],
        "srl32": ['rs2', 'rs1', 'rd'],
        "srl32.u": ['rs2', 'rs1', 'rd'],
        "srli32": ['imm5', 'rs1', 'rd'],
        "srli32.u": ['imm5', 'rs1', 'rd'],
        "stas32": ['rs2', 'rs1', 'rd'],
        "stsa32": ['rs2', 'rs1', 'rd'],
        "sub32": ['rs2', 'rs1', 'rd'],
        "ukadd32": ['rs2', 'rs1', 'rd'],
        "ukcras32": ['rs2', 'rs1', 'rd'],
        "ukcrsa32": ['rs2', 'rs1', 'rd'],
        "ukstas32": ['rs2', 'rs1', 'rd'],
        "ukstsa32": ['rs2', 'rs1', 'rd'],
        "uksub32": ['rs2', 'rs1', 'rd'],
        "umax32": ['rs2', 'rs1', 'rd'],
        "umin32": ['rs2', 'rs1', 'rd'],
        "uradd32": ['rs2', 'rs1', 'rd'],
        "urcras32": ['rs2', 'rs1', 'rd'],
        "urcrsa32": ['rs2', 'rs1', 'rd'],
        "urstas32": ['rs2', 'rs1', 'rd'],
        "urstsa32": ['rs2', 'rs1', 'rd'],
        "ursub32": ['rs2', 'rs1', 'rd'],
    },
    "rv32_zpsf": {
        "add64": ['rs2', 'rs1', 'rd'],
        "sub64": ['rs2', 'rs1', 'rd'],
    },
    "rv64_zba": {
        "add.uw": ['rd', 'rs1', 'rs2'],
        "sh1add.uw": ['rd', 'rs1', 'rs2'],
        "sh2add.uw": ['rd', 'rs1', 'rs2'],
        "sh3add.uw": ['rd', 'rs1', 'rs2'],
        "slli.uw": ['rd', 'rs1', 'shamtd'],
    },
    "rv128_i": {
        "addd": ['rd', 'rs1', 'rs2'],
        "addid": ['rd', 'rs1', 'imm12'],
        "ldu": ['rd', 'rs1', 'imm12'],
        "lq": ['rd', 'rs1', 'imm12'],
        "slld": ['rd', 'rs1', 'rs2'],
        "slli.rv128": ['rd', 'rs1', 'shamtq'],
        "sllid": ['rd', 'rs1', 'shamtd'],
        "sq": ['imm12hi', 'rs1', 'rs2', 'imm12lo'],
        "srad": ['rd', 'rs1', 'rs2'],
        "srai.rv128": ['rd', 'rs1', 'shamtq'],
        "sraid": ['rd', 'rs1', 'shamtd'],
        "srld": ['rd', 'rs1', 'rs2'],
        "srli.rv128": ['rd', 'rs1', 'shamtq'],
        "srlid": ['rd', 'rs1', 'shamtd'],
        "subd": ['rd', 'rs1', 'rs2'],
    },
    "rv64_i": {
        "addiw": ['rd', 'rs1', 'imm12'],
        "addw": ['rd', 'rs1', 'rs2'],
        "ld": ['rd', 'rs1', 'imm12'],
        "lwu": ['rd', 'rs1', 'imm12'],
        "sd": ['imm12hi', 'rs1', 'rs2', 'imm12lo'],
        "slli": ['rd', 'rs1', 'shamtd'],
        "slliw": ['rd', 'rs1', 'shamtw'],
        "sllw": ['rd', 'rs1', 'rs2'],
        "srai": ['rd', 'rs1', 'shamtd'],
        "sraiw": ['rd', 'rs1', 'shamtw'],
        "sraw": ['rd', 'rs1', 'rs2'],
        "srli": ['rd', 'rs1', 'shamtd'],
        "srliw": ['rd', 'rs1', 'shamtw'],
        "srlw": ['rd', 'rs1', 'rs2'],
        "subw": ['rd', 'rs1', 'rs2'],
    },
    "rv32_zk": {
        "aes32dsi": ['rd', 'rs1', 'rs2', 'bs'],
        "aes32dsmi": ['rd', 'rs1', 'rs2', 'bs'],
        "aes32esi": ['rd', 'rs1', 'rs2', 'bs'],
        "aes32esmi": ['rd', 'rs1', 'rs2', 'bs'],
        "sha512sig0h": ['rd', 'rs1', 'rs2'],
        "sha512sig0l": ['rd', 'rs1', 'rs2'],
        "sha512sig1h": ['rd', 'rs1', 'rs2'],
        "sha512sig1l": ['rd', 'rs1', 'rs2'],
        "sha512sum0r": ['rd', 'rs1', 'rs2'],
        "sha512sum1r": ['rd', 'rs1', 'rs2'],
    },
    "rv64_zk": {
        "aes64ds": ['rd', 'rs1', 'rs2'],
        "aes64dsm": ['rd', 'rs1', 'rs2'],
        "aes64es": ['rd', 'rs1', 'rs2'],
        "aes64esm": ['rd', 'rs1', 'rs2'],
        "aes64im": ['rd', 'rs1'],
        "aes64ks1i": ['rd', 'rs1', 'rnum'],
        "aes64ks2": ['rd', 'rs1', 'rs2'],
        "sha512sig0": ['rd', 'rs1'],
        "sha512sig1": ['rd', 'rs1'],
        "sha512sum0": ['rd', 'rs1'],
        "sha512sum1": ['rd', 'rs1'],
    },
    "rv64_a": {
        "amoadd.d": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amoand.d": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amomax.d": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amomaxu.d": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amomin.d": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amominu.d": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amoor.d": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amoswap.d": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amoxor.d": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "lr.d": ['rd', 'rs1', 'aq', 'rl'],
        "sc.d": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
    },
    "rv_a": {
        "amoadd.w": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amoand.w": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amomax.w": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amomaxu.w": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amomin.w": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amominu.w": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amoor.w": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amoswap.w": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "amoxor.w": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
        "lr.w": ['rd', 'rs1', 'aq', 'rl'],
        "sc.w": ['rd', 'rs1', 'rs2', 'aq', 'rl'],
    },
    "rv_zbkb": {
        "andn": ['rd', 'rs1', 'rs2'],
        "orn": ['rd', 'rs1', 'rs2'],
        "pack": ['rd', 'rs1', 'rs2'],
        "packh": ['rd', 'rs1', 'rs2'],
        "rol": ['rd', 'rs1', 'rs2'],
        "ror": ['rd', 'rs1', 'rs2'],
        "xnor": ['rd', 'rs1', 'rs2'],
    },
    "rv_zbs": {
        "bclr": ['rd', 'rs1', 'rs2'],
        "bext": ['rd', 'rs1', 'rs2'],
        "binv": ['rd', 'rs1', 'rs2'],
        "bset": ['rd', 'rs1', 'rs2'],
    },
    #gzhinsert
    "rv_32B": {
        "slo": ['rd', 'rs1', 'rs2'],
        "sro": ['rd', 'rs1', 'rs2'],
        "gorc": ['rd', 'rs1', 'rs2'],
        "shfl": ['rd', 'rs1', 'rs2'],
        "unshfl": ['rd', 'rs1', 'rs2'],
        "sh1add": ['rd', 'rs1', 'rs2'],
        "sh2add": ['rd', 'rs1', 'rs2'],
        "sh3add": ['rd', 'rs1', 'rs2'],
        "min": ['rd', 'rs1', 'rs2'],
        "max": ['rd', 'rs1', 'rs2'],
        "maxu": ['rd', 'rs1', 'rs2'],
        "minu": ['rd', 'rs1', 'rs2'],
        "sext.b": ['rd', 'rs1'],
        "sext.h": ['rd', 'rs1'],
     #   "ctz": ['rd', 'rs1'],
       # "sh3add": ['rd', 'rs1', 'rs2'],
        "bcompress": ['rd', 'rs1', 'rs2'],
        "bdecompress": ['rd', 'rs1', 'rs2'],
        "bfp": ['rd', 'rs1', 'rs2'],
        "clmulr": ['rd', 'rs1', 'rs2'],
        "crc32.b": ['rd', 'rs1'],
        "crc32.h": ['rd', 'rs1'],
        "crc32.w": ['rd', 'rs1'],
        "crc32c.b": ['rd', 'rs1'],
        "crc32c.w": ['rd', 'rs1'],
        "cpop": ['rd', 'rs1'],
        "minu": ['rd', 'rs1'],
        "xperm.n": ['rd', 'rs1', 'rs2'],
        "xperm.b": ['rd', 'rs1', 'rs2'],
        "xperm.h": ['rd', 'rs1', 'rs2'],
        "packu": ['rd', 'rs1', 'rs2'],
        "clz": ['rd', 'rs1'],
        "cmov": ['rd', 'rs1', 'rs2','rs3'],
        "cmix": ['rd', 'rs1', 'rs2','rs3'],
        "fsl": ['rd', 'rs1', 'rs2','rs3'],
        "fsr": ['rd', 'rs1', 'rs2','rs3'],
    },
    "rv64_zbs": {
        "bclri": ['rd', 'rs1', 'shamtd'],
        "bexti": ['rd', 'rs1', 'shamtd'],
        "binvi": ['rd', 'rs1', 'shamtd'],
        "bseti": ['rd', 'rs1', 'shamtd'],
    },
    "rv_zbe": {
        "bcompress": ['rd', 'rs1', 'rs2'],
        "bdecompress": ['rd', 'rs1', 'rs2'],
    },
    "rv64_zbe": {
        "bcompressw": ['rd', 'rs1', 'rs2'],
        "bdecompressw": ['rd', 'rs1', 'rs2'],
    },
    "rv_zbf": {
        "bfp": ['rd', 'rs1', 'rs2'],
    },
    "rv64_zbf": {
        "bfpw": ['rd', 'rs1', 'rs2'],
    },
    "rv64_zbm": {
        "bmatflip": ['rd', 'rs1'],
        "bmator": ['rd', 'rs1', 'rs2'],
        "bmatxor": ['rd', 'rs1', 'rs2'],
       # "packu": ['rd', 'rs1', 'rs2'],
        "unzip16": ['rd', 'rs1'],
        "unzip8": ['rd', 'rs1'],
    },
    "rv_zks": {
        "brev8": ['rd', 'rs1'],
        "sm3p0": ['rd', 'rs1'],
        "sm3p1": ['rd', 'rs1'],
        "sm4ed": ['rd', 'rs1', 'rs2', 'bs'],
        "sm4ks": ['rd', 'rs1', 'rs2', 'bs'],
    },
    "rv_c": {
        "c.add": ['rd.rs1', 'c.rs2.n0'],
        "c.addi": ['rd.rs1.n0', 'c.nzimm6lo', 'c.nzimm6hi'],
        "c.addi16sp": ['c.nzimm10hi', 'c.nzimm10lo'],
        "c.addi4spn": ['rd.p', 'c.nzuimm10'],
        "c.and": ['rd.rs1.p', 'rs2.p'],
        "c.andi": ['rd.rs1.p', 'c.imm6hi', 'c.imm6lo'],
        "c.beqz": ['rs1.p', 'c.bimm9lo', 'c.bimm9hi'],
        "c.bnez": ['rs1.p', 'c.bimm9lo', 'c.bimm9hi'],
        "c.ebreak": [],
        "c.j": ['c.imm12'],
        "c.jalr": ['c.rs1.n0'],
        "c.jr": ['rs1.n0'],
        "c.li": ['rd', 'c.imm6lo', 'c.imm6hi'],
        "c.lui": ['rd.n2', 'c.nzimm18hi', 'c.nzimm18lo'],# 错误，应该是17
        "c.lw": ['rd.p', 'rs1.p', 'c.uimm7lo', 'c.uimm7hi'],
        "c.lwsp": ['rd.n0', 'c.uimm8sphi', 'c.uimm8splo'],
        "c.mv": ['rd', 'c.rs2.n0'],
        "c.nop": ['c.nzimm6hi', 'c.nzimm6lo'],
        "c.or": ['rd.rs1.p', 'rs2.p'],
        "c.sub": ['rd.rs1.p', 'rs2.p'],
        "c.sw": ['rs1.p', 'rs2.p', 'c.uimm7lo', 'c.uimm7hi'],
        "c.swsp": ['c.rs2', 'c.uimm8sp.s'],
        "c.xor": ['rd.rs1.p', 'rs2.p'],
    },
    "rv64_c": {
        "c.addiw": ['rd.rs1', 'c.imm6lo', 'c.imm6hi'],
        "c.addw": ['rd.rs1.p', 'rs2.p'],
        "c.ld": ['rd.p', 'rs1.p', 'c.uimm8lo', 'c.uimm8hi'],
        "c.ldsp": ['rd.n0', 'c.uimm9sphi', 'c.uimm9splo'],
        "c.sd": ['rs1.p', 'rs2.p', 'c.uimm8hi', 'c.uimm8lo'],
        "c.sdsp": ['c.rs2', 'c.uimm9sp.s'],
        "c.slli": ['rd.rs1.n0', 'c.nzuimm6hi', 'c.nzuimm6lo'],
        "c.srai": ['rd.rs1.p', 'c.nzuimm6lo', 'c.nzuimm6hi'],
        "c.srli": ['rd.rs1.p', 'c.nzuimm6lo', 'c.nzuimm6hi'],
        "c.subw": ['rd.rs1.p', 'rs2.p'],
    },
    "rv_c_d": {
        "c.fld": ['rd.p', 'rs1.p', 'c.uimm8lo', 'c.uimm8hi'],
        "c.fldsp": ['rd', 'c.uimm9sphi', 'c.uimm9splo'],
        "c.fsd": ['rs1.p', 'rs2.p', 'c.uimm8lo', 'c.uimm8hi'],
        "c.fsdsp": ['c.rs2', 'c.uimm9sp.s'],
    },
    "rv32_c_f": {
        "c.flw": ['rd.p', 'rs1.p', 'c.uimm7lo', 'c.uimm7hi'],
        "c.flwsp": ['rd', 'c.uimm8sphi', 'c.uimm8splo'],
        "c.fsw": ['rs1.p', 'rs2.p', 'c.uimm7lo', 'c.uimm7hi'],
        "c.fswsp": ['c.rs2', 'c.uimm8sp.s'],
    },
    "rv32_c": {
        "c.jal": ['c.imm12'],
    },
    "rv_zcb": {# 未加
        "c.lbu": ['rd.p', 'rs1.p', 'c.uimm2'],
        "c.lh": ['rd.p', 'rs1.p', 'c.uimm1'],
        "c.lhu": ['rd.p', 'rs1.p', 'c.uimm1'],
        "c.mul": ['rd.rs1.p', 'rs2.p'],
        "c.not": ['rd.rs1.p'],
        "c.sb": ['rs2.p', 'rs1.p', 'c.uimm2'],
        "c.sext.b": ['rd.rs1.p'],
        "c.sext.h": ['rd.rs1.p'],
        "c.sh": ['rs2.p', 'rs1.p', 'c.uimm1'],
        "c.zext.b": ['rd.rs1.p'],
        "c.zext.h": ['rd.rs1.p'],
    },
    "rv128_c": {
        "c.lq": ['rd.p', 'rs1.p', 'c.uimm9lo', 'c.uimm9hi'],
        "c.lqsp": ['rd', 'c.uimm10sphi', 'c.uimm10splo'],
        "c.sq": ['rs1.p', 'rs2.p', 'c.uimm9hi', 'c.uimm9lo'],
        "c.sqsp": ['c.rs2', 'c.uimm10sp.s'],
    },
    "rv_c_zihintntl": {
        "c.ntl.all": [],
        "c.ntl.p1": [],
        "c.ntl.pall": [],
        "c.ntl.s1": [],
    },
    "rv64_zcb": {
        "c.zext.w": ['rd.rs1.p'],
    },
    "rv_zicbo": {
        "cbo.clean": ['rs1'],
        "cbo.flush": ['rs1'],
        "cbo.inval": ['rs1'],
        "cbo.zero": ['rs1'],
        "prefetch.i": ['rs1', 'imm12hi'],
        "prefetch.r": ['rs1', 'imm12hi'],
        "prefetch.w": ['rs1', 'imm12hi'],
    },
    "rv_zbkc": {
        "clmul": ['rd', 'rs1', 'rs2'],
        "clmulh": ['rd', 'rs1', 'rs2'],
    },
    "rv_zbc": {
        "clmulr": ['rd', 'rs1', 'rs2'],
    },
    # "rv32_zbpbo": {
    #     "clz": ['rd', 'rs1'],
    #     "fsr": ['rd', 'rs1', 'rs2', 'rs3'],
    # },
    "rv64_zbb": {
        "clzw": ['rd', 'rs1'],
        "cpopw": ['rd', 'rs1'],
        "ctzw": ['rd', 'rs1'],
        "zext.h": ['rd', 'rs1'],
    },
    "rv_zcmt": {
        "cm.jalt": ['c.index'],
    },
    "rv_zcmp": {
        "cm.mva01s": ['c.sreg1', 'c.sreg2'],
        "cm.mvsa01": ['c.sreg1', 'c.sreg2'],
        "cm.pop": ['c.rlist', 'c.spimm'],
        "cm.popret": ['c.rlist', 'c.spimm'],
        "cm.popretz": ['c.rlist', 'c.spimm'],
        "cm.push": ['c.rlist', 'c.spimm'],
    },
    "rv_zbpbo": {
      #  "cmix": ['rd', 'rs1', 'rs2', 'rs3'],
        "grev": ['rd', 'rs1', 'rs2'],
        "max": ['rd', 'rs1', 'rs2'],
        "min": ['rd', 'rs1', 'rs2'],
        "rev8.h": ['rd', 'rs1'],
    },
    # "rv_zbt": {
    #     "cmov": ['rd', 'rs1', 'rs2', 'rs3'],
    #     "fsl": ['rd', 'rs1', 'rs2', 'rs3'],
    # },
    "rv_zbb": {
        "cpop": ['rd', 'rs1'],
       # "ctz": ['rd', 'rs1'],
        "maxu": ['rd', 'rs1', 'rs2'],
        "minu": ['rd', 'rs1', 'rs2'],
        "orc.b": ['rd', 'rs1'],
        "sext.b": ['rd', 'rs1'],
        "sext.h": ['rd', 'rs1'],
    },
    "rv_zbr": {
        "crc32.b": ['rd', 'rs1'],
        "crc32.h": ['rd', 'rs1'],
        "crc32.w": ['rd', 'rs1'],
        "crc32c.b": ['rd', 'rs1'],
        "crc32c.h": ['rd', 'rs1'],
        "crc32c.w": ['rd', 'rs1'],
    },
    "rv64_zbr": {
        "crc32.d": ['rd', 'rs1'],
        "crc32c.d": ['rd', 'rs1'],
    },
    "rv_zicsr": {
        "csrrc": ['rd', 'rs1', 'csr'],
        "csrrci": ['rd', 'csr', 'zimm'],
        "csrrs": ['rd', 'rs1', 'csr'],
        "csrrsi": ['rd', 'csr', 'zimm'],
        "csrrw": ['rd', 'rs1', 'csr'],
        "csrrwi": ['rd', 'csr', 'zimm'],
        "frcsr": ['rd'],
        "frflags": ['rd'],
        "frrm": ['rd'],
        "fscsr": ['rd', 'rs1'],
        "fsflags": ['rd', 'rs1'],
        "fsflagsi": ['rd', 'zimm'],
        "fsrm": ['rd', 'rs1'],
        "fsrmi": ['rd', 'zimm'],
        "rdcycle": ['rd'],
        "rdcycleh": ['rd'],
        "rdinstret": ['rd'],
        "rdinstreth": ['rd'],
        "rdtime": ['rd'],
        "rdtimeh": ['rd'],
    },
    "rv_zicond": {
        "czero.eqz": ['rd', 'rs1', 'rs2'],
        "czero.nez": ['rd', 'rs1', 'rs2'],
    },
    "rv_m": {
        "div": ['rd', 'rs1', 'rs2'],
        "divu": ['rd', 'rs1', 'rs2'],
        "mul": ['rd', 'rs1', 'rs2'],
        "mulhsu": ['rd', 'rs1', 'rs2'],
        "mulhu": ['rd', 'rs1', 'rs2'],
        "rem": ['rd', 'rs1', 'rs2'],
        "remu": ['rd', 'rs1', 'rs2'],
    },
    "rv64_m": {
        "divuw": ['rd', 'rs1', 'rs2'],
        "divw": ['rd', 'rs1', 'rs2'],
        "mulw": ['rd', 'rs1', 'rs2'],
        "remuw": ['rd', 'rs1', 'rs2'],
        "remw": ['rd', 'rs1', 'rs2'],
    },
    "rv_system": {
        "dret": [],
        "mret": [],
        "wfi": [],
    },
    "rv_d": {
        "fadd.d": ['rd', 'rs1', 'rs2', 'rm'],
        "fclass.d": ['rd', 'rs1'],
        "fcvt.d.s": ['rd', 'rs1', 'rm'],
        "fcvt.d.w": ['rd', 'rs1', 'rm'],
        "fcvt.d.wu": ['rd', 'rs1', 'rm'],
        "fcvt.s.d": ['rd', 'rs1', 'rm'],
        "fcvt.w.d": ['rd', 'rs1', 'rm'],
        "fcvt.wu.d": ['rd', 'rs1', 'rm'],
        "fdiv.d": ['rd', 'rs1', 'rs2', 'rm'],
        "feq.d": ['rd', 'rs1', 'rs2'],
        "fld": ['rd', 'rs1', 'imm12'],
        "fle.d": ['rd', 'rs1', 'rs2'],
        "flt.d": ['rd', 'rs1', 'rs2'],
        "fmadd.d": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fmax.d": ['rd', 'rs1', 'rs2'],
        "fmin.d": ['rd', 'rs1', 'rs2'],
        "fmsub.d": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fmul.d": ['rd', 'rs1', 'rs2', 'rm'],
        "fnmadd.d": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fnmsub.d": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fsd": ['imm12hi', 'rs1', 'rs2', 'imm12lo'],
        "fsgnj.d": ['rd', 'rs1', 'rs2'],
        "fsgnjn.d": ['rd', 'rs1', 'rs2'],
        "fsgnjx.d": ['rd', 'rs1', 'rs2'],
        "fsqrt.d": ['rd', 'rs1', 'rm'],
        "fsub.d": ['rd', 'rs1', 'rs2', 'rm'],
    },
    "rv_zfh": {
        "fadd.h": ['rd', 'rs1', 'rs2', 'rm'],
        "fclass.h": ['rd', 'rs1'],
        "fcvt.h.s": ['rd', 'rs1', 'rm'],
        "fcvt.h.w": ['rd', 'rs1', 'rm'],
        "fcvt.h.wu": ['rd', 'rs1', 'rm'],
        "fcvt.s.h": ['rd', 'rs1', 'rm'],
        "fcvt.w.h": ['rd', 'rs1', 'rm'],
        "fcvt.wu.h": ['rd', 'rs1', 'rm'],
        "fdiv.h": ['rd', 'rs1', 'rs2', 'rm'],
        "feq.h": ['rd', 'rs1', 'rs2'],
        "fle.h": ['rd', 'rs1', 'rs2'],
        "flh": ['rd', 'rs1', 'imm12'],
        "flt.h": ['rd', 'rs1', 'rs2'],
        "fmadd.h": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fmax.h": ['rd', 'rs1', 'rs2'],
        "fmin.h": ['rd', 'rs1', 'rs2'],
        "fmsub.h": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fmul.h": ['rd', 'rs1', 'rs2', 'rm'],
        "fmv.h.x": ['rd', 'rs1'],
        "fmv.x.h": ['rd', 'rs1'],
        "fnmadd.h": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fnmsub.h": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fsgnj.h": ['rd', 'rs1', 'rs2'],
        "fsgnjn.h": ['rd', 'rs1', 'rs2'],
        "fsgnjx.h": ['rd', 'rs1', 'rs2'],
        "fsh": ['imm12hi', 'rs1', 'rs2', 'imm12lo'],
        "fsqrt.h": ['rd', 'rs1', 'rm'],
        "fsub.h": ['rd', 'rs1', 'rs2', 'rm'],
    },
    "rv_q": {
        "fadd.q": ['rd', 'rs1', 'rs2', 'rm'],
        "fclass.q": ['rd', 'rs1'],
        "fcvt.d.q": ['rd', 'rs1', 'rm'],
        "fcvt.q.d": ['rd', 'rs1', 'rm'],
        "fcvt.q.s": ['rd', 'rs1', 'rm'],
        "fcvt.q.w": ['rd', 'rs1', 'rm'],
        "fcvt.q.wu": ['rd', 'rs1', 'rm'],
        "fcvt.s.q": ['rd', 'rs1', 'rm'],
        "fcvt.w.q": ['rd', 'rs1', 'rm'],
        "fcvt.wu.q": ['rd', 'rs1', 'rm'],
        "fdiv.q": ['rd', 'rs1', 'rs2', 'rm'],
        "feq.q": ['rd', 'rs1', 'rs2'],
        "fle.q": ['rd', 'rs1', 'rs2'],
        "flq": ['rd', 'rs1', 'imm12'],
        "flt.q": ['rd', 'rs1', 'rs2'],
        "fmadd.q": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fmax.q": ['rd', 'rs1', 'rs2'],
        "fmin.q": ['rd', 'rs1', 'rs2'],
        "fmsub.q": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fmul.q": ['rd', 'rs1', 'rs2', 'rm'],
        "fnmadd.q": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fnmsub.q": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fsgnj.q": ['rd', 'rs1', 'rs2'],
        "fsgnjn.q": ['rd', 'rs1', 'rs2'],
        "fsgnjx.q": ['rd', 'rs1', 'rs2'],
        "fsq": ['imm12hi', 'rs1', 'rs2', 'imm12lo'],
        "fsqrt.q": ['rd', 'rs1', 'rm'],
        "fsub.q": ['rd', 'rs1', 'rs2', 'rm'],
    },
    "rv_f": {
        "fadd.s": ['rd', 'rs1', 'rs2', 'rm'],
        "fclass.s": ['rd', 'rs1'],
        "fcvt.s.w": ['rd', 'rs1', 'rm'],
        "fcvt.s.wu": ['rd', 'rs1', 'rm'],
        "fcvt.w.s": ['rd', 'rs1', 'rm'],
        "fcvt.wu.s": ['rd', 'rs1', 'rm'],
        "fdiv.s": ['rd', 'rs1', 'rs2', 'rm'],
        "feq.s": ['rd', 'rs1', 'rs2'],
        "fle.s": ['rd', 'rs1', 'rs2'],
        "flt.s": ['rd', 'rs1', 'rs2'],
        "flw": ['rd', 'rs1', 'imm12'],
        "fmadd.s": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fmax.s": ['rd', 'rs1', 'rs2'],
        "fmin.s": ['rd', 'rs1', 'rs2'],
        "fmsub.s": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fmul.s": ['rd', 'rs1', 'rs2', 'rm'],
        "fmv.s.x": ['rd', 'rs1'],
        "fmv.w.x": ['rd', 'rs1'],
        "fmv.x.s": ['rd', 'rs1'],
        "fmv.x.w": ['rd', 'rs1'],
        "fnmadd.s": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fnmsub.s": ['rd', 'rs1', 'rs2', 'rs3', 'rm'],
        "fsgnj.s": ['rd', 'rs1', 'rs2'],
        "fsgnjn.s": ['rd', 'rs1', 'rs2'],
        "fsgnjx.s": ['rd', 'rs1', 'rs2'],
        "fsqrt.s": ['rd', 'rs1', 'rm'],
        "fsub.s": ['rd', 'rs1', 'rs2', 'rm'],
        "fsw": ['imm12hi', 'rs1', 'rs2', 'imm12lo'],
    },
    "rv_d_zfh": {
        "fcvt.d.h": ['rd', 'rs1', 'rm'],
        "fcvt.h.d": ['rd', 'rs1', 'rm'],
    },
    "rv64_d": {
        "fcvt.d.l": ['rd', 'rs1', 'rm'],
        "fcvt.d.lu": ['rd', 'rs1', 'rm'],
        "fcvt.l.d": ['rd', 'rs1', 'rm'],
        "fcvt.lu.d": ['rd', 'rs1', 'rm'],
        "fmv.d.x": ['rd', 'rs1'],
        "fmv.x.d": ['rd', 'rs1'],
    },
    "rv64.zfh": {
        "fcvt.h.l": ['rd', 'rs1', 'rm'],
        "fcvt.h.lu": ['rd', 'rs1', 'rm'],
        "fcvt.l.h": ['rd', 'rs1', 'rm'],
        "fcvt.lu.h": ['rd', 'rs1', 'rm'],
    },
    "rv_q_zfh": {
        "fcvt.h.q": ['rd', 'rs1', 'rm'],
        "fcvt.q.h": ['rd', 'rs1', 'rm'],
    },
    "rv64_q": {
        "fcvt.l.q": ['rd', 'rs1', 'rm'],
        "fcvt.lu.q": ['rd', 'rs1', 'rm'],
        "fcvt.q.l": ['rd', 'rs1', 'rm'],
        "fcvt.q.lu": ['rd', 'rs1', 'rm'],
    },
    "rv64_f": {
        "fcvt.l.s": ['rd', 'rs1', 'rm'],
        "fcvt.lu.s": ['rd', 'rs1', 'rm'],
        "fcvt.s.l": ['rd', 'rs1', 'rm'],
        "fcvt.s.lu": ['rd', 'rs1', 'rm'],
    },
    "rv_zifencei": {
        "fence.i": ['imm12', 'rs1', 'rd'],
    },
    "rv64_zbt": {
        "fslw": ['rd', 'rs1', 'rs2', 'rs3'],
        "fsri": ['rd', 'rs1', 'rs3', 'shamtd'],
        "fsriw": ['rd', 'rs1', 'rs3', 'shamtw'],
    },
    "rv64_zbpbo": {
        "fsrw": ['rd', 'rs1', 'rs2', 'rs3'],
        "grevi": ['rd', 'rs1', 'shamtd'],
        "rev": ['rd', 'rs1'],
    },
    "rv_zbp": {
        "gorc": ['rd', 'rs1', 'rs2'],
        "shfl": ['rd', 'rs1', 'rs2'],
        "unshfl": ['rd', 'rs1', 'rs2'],
        "xperm16": ['rd', 'rs1', 'rs2'],
    },
    "rv64_zbp": {
        "gorci": ['rd', 'rs1', 'shamtd'],
        "gorciw": ['rd', 'rs1', 'shamtw'],
        "gorcw": ['rd', 'rs1', 'rs2'],
        "greviw": ['rd', 'rs1', 'shamtw'],
        "grevw": ['rd', 'rs1', 'rs2'],
        "packuw": ['rd', 'rs1', 'rs2'],
        "shfli": ['rd', 'rs1', 'shamtw'],
        "shflw": ['rd', 'rs1', 'rs2'],
        "unshfli": ['rd', 'rs1', 'shamtw'],
        "unshflw": ['rd', 'rs1', 'rs2'],
        "xperm32": ['rd', 'rs1', 'rs2'],
    },
    "rv_h": {
        "hfence.gvma": ['rs1', 'rs2'],
        "hfence.vvma": ['rs1', 'rs2'],
        "hlv.b": ['rd', 'rs1'],
        "hlv.bu": ['rd', 'rs1'],
        "hlv.h": ['rd', 'rs1'],
        "hlv.hu": ['rd', 'rs1'],
        "hlv.w": ['rd', 'rs1'],
        "hlvx.hu": ['rd', 'rs1'],
        "hlvx.wu": ['rd', 'rs1'],
        "hsv.b": ['rs1', 'rs2'],
        "hsv.h": ['rs1', 'rs2'],
        "hsv.w": ['rs1', 'rs2'],
    },
    "rv_svinval": {
        "hinval.gvma": ['rs1', 'rs2'],
        "hinval.vvma": ['rs1', 'rs2'],
        "sfence.inval.ir": [],
        "sfence.w.inval": [],
        "sinval.vma": ['rs1', 'rs2'],
    },
    "rv64_h": {
        "hlv.d": ['rd', 'rs1'],
        "hlv.wu": ['rd', 'rs1'],
        "hsv.d": ['rs1', 'rs2'],
    },
    "rv_zpsf": {
        "kadd64": ['rs2', 'rs1', 'rd'],
        "kmar64": ['rs2', 'rs1', 'rd'],
        "kmsr64": ['rs2', 'rs1', 'rd'],
        "ksub64": ['rs2', 'rs1', 'rd'],
        "mulr64": ['rs2', 'rs1', 'rd'],
        "mulsr64": ['rs2', 'rs1', 'rd'],
        "radd64": ['rs2', 'rs1', 'rd'],
        "rsub64": ['rs2', 'rs1', 'rd'],
        "smal": ['rs2', 'rs1', 'rd'],
        "smalbb": ['rs2', 'rs1', 'rd'],
        "smalbt": ['rs2', 'rs1', 'rd'],
        "smalda": ['rs2', 'rs1', 'rd'],
        "smaldrs": ['rs2', 'rs1', 'rd'],
        "smalds": ['rs2', 'rs1', 'rd'],
        "smaltt": ['rs2', 'rs1', 'rd'],
        "smalxda": ['rs2', 'rs1', 'rd'],
        "smalxds": ['rs2', 'rs1', 'rd'],
        "smar64": ['rs2', 'rs1', 'rd'],
        "smslda": ['rs2', 'rs1', 'rd'],
        "smslxda": ['rs2', 'rs1', 'rd'],
        "smsr64": ['rs2', 'rs1', 'rd'],
        "smul16": ['rs2', 'rs1', 'rd'],
        "smul8": ['rs2', 'rs1', 'rd'],
        "smulx16": ['rs2', 'rs1', 'rd'],
        "smulx8": ['rs2', 'rs1', 'rd'],
        "ukadd64": ['rs2', 'rs1', 'rd'],
        "ukmar64": ['rs2', 'rs1', 'rd'],
        "ukmsr64": ['rs2', 'rs1', 'rd'],
        "uksub64": ['rs2', 'rs1', 'rd'],
        "umar64": ['rs2', 'rs1', 'rd'],
        "umsr64": ['rs2', 'rs1', 'rd'],
        "umul16": ['rs2', 'rs1', 'rd'],
        "umul8": ['rs2', 'rs1', 'rd'],
        "umulx16": ['rs2', 'rs1', 'rd'],
        "umulx8": ['rs2', 'rs1', 'rd'],
        "uradd64": ['rs2', 'rs1', 'rd'],
        "ursub64": ['rs2', 'rs1', 'rd'],
    },
    "rv32_zpn": {
        "mulh": ['rd', 'rs1', 'rs2'],
    },
    "rv_zihintntl": {
        "ntl.all": [],
        "ntl.p1": [],
        "ntl.pall": [],
        "ntl.s1": [],
    },
    "rv64_zbkb": {
        "packw": ['rd', 'rs1', 'rs2'],
        "rolw": ['rd', 'rs1', 'rs2'],
        "rori": ['rd', 'rs1', 'shamtd'],
        "roriw": ['rd', 'rs1', 'shamtw'],
        "rorw": ['rd', 'rs1', 'rs2'],
    },
    "rv64_zks": {
        "rev8": ['rd', 'rs1'],
    },
    "rv_s": {
        "sfence.vma": ['rs1', 'rs2'],
        "sret": [],
    },
    "rv_zba": {
        "sh1add": ['rd', 'rs1', 'rs2'],
        "sh2add": ['rd', 'rs1', 'rs2'],
        "sh3add": ['rd', 'rs1', 'rs2'],
    },
    "rv_zk": {
        "sha256sig0": ['rd', 'rs1'],
        "sha256sig1": ['rd', 'rs1'],
        "sha256sum0": ['rd', 'rs1'],
        "sha256sum1": ['rd', 'rs1'],
    },
    "rv32_i": {
        "slli.rv32": ['rd', 'rs1', 'shamtw'],
        "srai.rv32": ['rd', 'rs1', 'shamtw'],
        "srli.rv32": ['rd', 'rs1', 'shamtw'],
    },
    "rv_b": {
        "slo": ['rd', 'rs1', 'rs2'],
        "sloi": ['rd', 'rs1', 'shamtd'],
        "sro": ['rd', 'rs1', 'rs2'],
        "sroi": ['rd', 'rs1', 'shamtd'],
    },
    "rv64_b": {
        "sloiw": ['rd', 'rs1', 'shamtw'],
        "slow": ['rd', 'rs1', 'rs2'],
        "sroiw": ['rd', 'rs1', 'shamtw'],
        "srow": ['rd', 'rs1', 'rs2'],
    },
    "rv32_zks": {
        "unzip": ['rd', 'rs1'],
        "zip": ['rd', 'rs1'],
    },
    "rv_v": {
        "vaadd.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vaadd.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vaaddu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vaaddu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vadc.vim": ['vs2', 'simm5', 'vd'],
        "vadc.vvm": ['vs2', 'vs1', 'vd'],
        "vadc.vxm": ['vs2', 'rs1', 'vd'],
        "vadd.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vadd.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vadd.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vamoaddei16.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoaddei32.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoaddei64.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoaddei8.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoandei16.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoandei32.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoandei64.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoandei8.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamomaxei16.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamomaxei32.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamomaxei64.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamomaxei8.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamomaxuei16.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamomaxuei32.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamomaxuei64.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamomaxuei8.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamominei16.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamominei32.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamominei64.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamominei8.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamominuei16.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamominuei32.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamominuei64.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamominuei8.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoorei16.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoorei32.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoorei64.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoorei8.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoswapei16.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoswapei32.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoswapei64.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoswapei8.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoxorei16.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoxorei32.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoxorei64.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vamoxorei8.v": ['wd', 'vm', 'vs2', 'rs1', 'vd'],
        "vand.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vand.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vand.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vasub.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vasub.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vasubu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vasubu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vcompress.vm": ['vs2', 'vs1', 'vd'],
        "vcpop.m": ['vm', 'vs2', 'rd'],
        "vdiv.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vdiv.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vdivu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vdivu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vfadd.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfadd.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfclass.v": ['vm', 'vs2', 'vd'],
        "vfcvt.f.x.v": ['vm', 'vs2', 'vd'],
        "vfcvt.f.xu.v": ['vm', 'vs2', 'vd'],
        "vfcvt.rtz.x.f.v": ['vm', 'vs2', 'vd'],
        "vfcvt.rtz.xu.f.v": ['vm', 'vs2', 'vd'],
        "vfcvt.x.f.v": ['vm', 'vs2', 'vd'],
        "vfcvt.xu.f.v": ['vm', 'vs2', 'vd'],
        "vfdiv.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfdiv.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfirst.m": ['vm', 'vs2', 'rd'],
        "vfmacc.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfmacc.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfmadd.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfmadd.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfmax.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfmax.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfmerge.vfm": ['vs2', 'rs1', 'vd'],
        "vfmin.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfmin.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfmsac.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfmsac.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfmsub.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfmsub.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfmul.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfmul.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfmv.f.s": ['vs2', 'rd'],
        "vfmv.s.f": ['rs1', 'vd'],
        "vfmv.v.f": ['rs1', 'vd'],
        "vfncvt.f.f.w": ['vm', 'vs2', 'vd'],
        "vfncvt.f.x.w": ['vm', 'vs2', 'vd'],
        "vfncvt.f.xu.w": ['vm', 'vs2', 'vd'],
        "vfncvt.rod.f.f.w": ['vm', 'vs2', 'vd'],
        "vfncvt.rtz.x.f.w": ['vm', 'vs2', 'vd'],
        "vfncvt.rtz.xu.f.w": ['vm', 'vs2', 'vd'],
        "vfncvt.x.f.w": ['vm', 'vs2', 'vd'],
        "vfncvt.xu.f.w": ['vm', 'vs2', 'vd'],
        "vfnmacc.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfnmacc.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfnmadd.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfnmadd.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfnmsac.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfnmsac.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfnmsub.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfnmsub.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfrdiv.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfrec7.v": ['vm', 'vs2', 'vd'],
        "vfredmax.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vfredmin.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vfredosum.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vfredusum.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vfrsqrt7.v": ['vm', 'vs2', 'vd'],
        "vfrsub.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfsgnj.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfsgnj.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfsgnjn.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfsgnjn.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfsgnjx.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfsgnjx.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfslide1down.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfslide1up.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfsqrt.v": ['vm', 'vs2', 'vd'],
        "vfsub.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfsub.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfwadd.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfwadd.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfwadd.wf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfwadd.wv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfwcvt.f.f.v": ['vm', 'vs2', 'vd'],
        "vfwcvt.f.x.v": ['vm', 'vs2', 'vd'],
        "vfwcvt.f.xu.v": ['vm', 'vs2', 'vd'],
        "vfwcvt.rtz.x.f.v": ['vm', 'vs2', 'vd'],
        "vfwcvt.rtz.xu.f.v": ['vm', 'vs2', 'vd'],
        "vfwcvt.x.f.v": ['vm', 'vs2', 'vd'],
        "vfwcvt.xu.f.v": ['vm', 'vs2', 'vd'],
        "vfwmacc.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfwmacc.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfwmsac.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfwmsac.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfwmul.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfwmul.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfwnmacc.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfwnmacc.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfwnmsac.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfwnmsac.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfwredosum.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vfwredusum.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vfwsub.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfwsub.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vfwsub.wf": ['vm', 'vs2', 'rs1', 'vd'],
        "vfwsub.wv": ['vm', 'vs2', 'vs1', 'vd'],
        "vid.v": ['vm', 'vd'],
        "viota.m": ['vm', 'vs2', 'vd'],
        "vl1re16.v": ['rs1', 'vd'],
        "vl1re32.v": ['rs1', 'vd'],
        "vl1re64.v": ['rs1', 'vd'],
        "vl1re8.v": ['rs1', 'vd'],
        "vl2re16.v": ['rs1', 'vd'],
        "vl2re32.v": ['rs1', 'vd'],
        "vl2re64.v": ['rs1', 'vd'],
        "vl2re8.v": ['rs1', 'vd'],
        "vl4re16.v": ['rs1', 'vd'],
        "vl4re32.v": ['rs1', 'vd'],
        "vl4re64.v": ['rs1', 'vd'],
        "vl4re8.v": ['rs1', 'vd'],
        "vl8re16.v": ['rs1', 'vd'],
        "vl8re32.v": ['rs1', 'vd'],
        "vl8re64.v": ['rs1', 'vd'],
        "vl8re8.v": ['rs1', 'vd'],
        "vle1024.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle1024ff.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle128.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle128ff.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle16.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle16ff.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle256.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle256ff.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle32.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle32ff.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle512.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle512ff.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle64.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle64ff.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle8.v": ['nf', 'vm', 'rs1', 'vd'],
        "vle8ff.v": ['nf', 'vm', 'rs1', 'vd'],
        "vlm.v": ['rs1', 'vd'],
        "vloxei1024.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vloxei128.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vloxei16.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vloxei256.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vloxei32.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vloxei512.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vloxei64.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vloxei8.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vlse1024.v": ['nf', 'vm', 'rs2', 'rs1', 'vd'],
        "vlse128.v": ['nf', 'vm', 'rs2', 'rs1', 'vd'],
        "vlse16.v": ['nf', 'vm', 'rs2', 'rs1', 'vd'],
        "vlse256.v": ['nf', 'vm', 'rs2', 'rs1', 'vd'],
        "vlse32.v": ['nf', 'vm', 'rs2', 'rs1', 'vd'],
        "vlse512.v": ['nf', 'vm', 'rs2', 'rs1', 'vd'],
        "vlse64.v": ['nf', 'vm', 'rs2', 'rs1', 'vd'],
        "vlse8.v": ['nf', 'vm', 'rs2', 'rs1', 'vd'],
        "vluxei1024.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vluxei128.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vluxei16.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vluxei256.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vluxei32.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vluxei512.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vluxei64.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vluxei8.v": ['nf', 'vm', 'vs2', 'rs1', 'vd'],
        "vmacc.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmacc.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmadc.vi": ['vs2', 'simm5', 'vd'],
        "vmadc.vim": ['vs2', 'simm5', 'vd'],
        "vmadc.vv": ['vs2', 'vs1', 'vd'],
        "vmadc.vvm": ['vs2', 'vs1', 'vd'],
        "vmadc.vx": ['vs2', 'rs1', 'vd'],
        "vmadc.vxm": ['vs2', 'rs1', 'vd'],
        "vmadd.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmadd.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmand.mm": ['vm', 'vs2', 'vs1', 'vd'],
        "vmandn.mm": ['vm', 'vs2', 'vs1', 'vd'],
        "vmax.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmax.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmaxu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmaxu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmerge.vim": ['vs2', 'simm5', 'vd'],
        "vmerge.vvm": ['vs2', 'vs1', 'vd'],
        "vmerge.vxm": ['vs2', 'rs1', 'vd'],
        "vmfeq.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vmfeq.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmfge.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vmfgt.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vmfle.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vmfle.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmflt.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vmflt.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmfne.vf": ['vm', 'vs2', 'rs1', 'vd'],
        "vmfne.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmin.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmin.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vminu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vminu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmnand.mm": ['vm', 'vs2', 'vs1', 'vd'],
        "vmnor.mm": ['vm', 'vs2', 'vs1', 'vd'],
        "vmor.mm": ['vm', 'vs2', 'vs1', 'vd'],
        "vmorn.mm": ['vm', 'vs2', 'vs1', 'vd'],
        "vmsbc.vv": ['vs2', 'vs1', 'vd'],
        "vmsbc.vvm": ['vs2', 'vs1', 'vd'],
        "vmsbc.vx": ['vs2', 'rs1', 'vd'],
        "vmsbc.vxm": ['vs2', 'rs1', 'vd'],
        "vmsbf.m": ['vm', 'vs2', 'vd'],
        "vmseq.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vmseq.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmseq.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmsgt.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vmsgt.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmsgtu.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vmsgtu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmsif.m": ['vm', 'vs2', 'vd'],
        "vmsle.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vmsle.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmsle.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmsleu.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vmsleu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmsleu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmslt.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmslt.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmsltu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmsltu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmsne.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vmsne.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmsne.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmsof.m": ['vm', 'vs2', 'vd'],
        "vmul.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmul.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmulh.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmulh.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmulhsu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmulhsu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmulhu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vmulhu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vmv1r.v": ['vs2', 'vd'],
        "vmv2r.v": ['vs2', 'vd'],
        "vmv4r.v": ['vs2', 'vd'],
        "vmv8r.v": ['vs2', 'vd'],
        "vmv.s.x": ['rs1', 'vd'],
        "vmv.v.i": ['simm5', 'vd'],
        "vmv.v.v": ['vs1', 'vd'],
        "vmv.v.x": ['rs1', 'vd'],
        "vmv.x.s": ['vs2', 'rd'],
        "vmxnor.mm": ['vm', 'vs2', 'vs1', 'vd'],
        "vmxor.mm": ['vm', 'vs2', 'vs1', 'vd'],
        "vnclip.wi": ['vm', 'vs2', 'simm5', 'vd'],
        "vnclip.wv": ['vm', 'vs2', 'vs1', 'vd'],
        "vnclip.wx": ['vm', 'vs2', 'rs1', 'vd'],
        "vnclipu.wi": ['vm', 'vs2', 'simm5', 'vd'],
        "vnclipu.wv": ['vm', 'vs2', 'vs1', 'vd'],
        "vnclipu.wx": ['vm', 'vs2', 'rs1', 'vd'],
        "vnmsac.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vnmsac.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vnmsub.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vnmsub.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vnsra.wi": ['vm', 'vs2', 'simm5', 'vd'],
        "vnsra.wv": ['vm', 'vs2', 'vs1', 'vd'],
        "vnsra.wx": ['vm', 'vs2', 'rs1', 'vd'],
        "vnsrl.wi": ['vm', 'vs2', 'simm5', 'vd'],
        "vnsrl.wv": ['vm', 'vs2', 'vs1', 'vd'],
        "vnsrl.wx": ['vm', 'vs2', 'rs1', 'vd'],
        "vor.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vor.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vor.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vredand.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vredmax.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vredmaxu.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vredmin.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vredminu.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vredor.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vredsum.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vredxor.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vrem.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vrem.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vremu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vremu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vrgather.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vrgather.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vrgather.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vrgatherei16.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vrsub.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vrsub.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vs1r.v": ['rs1', 'vs3'],
        "vs2r.v": ['rs1', 'vs3'],
        "vs4r.v": ['rs1', 'vs3'],
        "vs8r.v": ['rs1', 'vs3'],
        "vsadd.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vsadd.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vsadd.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vsaddu.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vsaddu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vsaddu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vsbc.vvm": ['vs2', 'vs1', 'vd'],
        "vsbc.vxm": ['vs2', 'rs1', 'vd'],
        "vse1024.v": ['nf', 'vm', 'rs1', 'vs3'],
        "vse128.v": ['nf', 'vm', 'rs1', 'vs3'],
        "vse16.v": ['nf', 'vm', 'rs1', 'vs3'],
        "vse256.v": ['nf', 'vm', 'rs1', 'vs3'],
        "vse32.v": ['nf', 'vm', 'rs1', 'vs3'],
        "vse512.v": ['nf', 'vm', 'rs1', 'vs3'],
        "vse64.v": ['nf', 'vm', 'rs1', 'vs3'],
        "vse8.v": ['nf', 'vm', 'rs1', 'vs3'],
        "vsetivli": ['zimm10', 'zimm', 'rd'],
        "vsetvl": ['rs2', 'rs1', 'rd'],
        "vsetvli": ['zimm11', 'rs1', 'rd'],
        "vsext.vf2": ['vm', 'vs2', 'vd'],
        "vsext.vf4": ['vm', 'vs2', 'vd'],
        "vsext.vf8": ['vm', 'vs2', 'vd'],
        "vslide1down.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vslide1up.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vslidedown.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vslidedown.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vslideup.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vslideup.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vsll.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vsll.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vsll.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vsm.v": ['rs1', 'vs3'],
        "vsmul.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vsmul.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vsoxei1024.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsoxei128.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsoxei16.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsoxei256.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsoxei32.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsoxei512.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsoxei64.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsoxei8.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsra.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vsra.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vsra.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vsrl.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vsrl.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vsrl.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vsse1024.v": ['nf', 'vm', 'rs2', 'rs1', 'vs3'],
        "vsse128.v": ['nf', 'vm', 'rs2', 'rs1', 'vs3'],
        "vsse16.v": ['nf', 'vm', 'rs2', 'rs1', 'vs3'],
        "vsse256.v": ['nf', 'vm', 'rs2', 'rs1', 'vs3'],
        "vsse32.v": ['nf', 'vm', 'rs2', 'rs1', 'vs3'],
        "vsse512.v": ['nf', 'vm', 'rs2', 'rs1', 'vs3'],
        "vsse64.v": ['nf', 'vm', 'rs2', 'rs1', 'vs3'],
        "vsse8.v": ['nf', 'vm', 'rs2', 'rs1', 'vs3'],
        "vssra.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vssra.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vssra.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vssrl.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vssrl.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vssrl.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vssub.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vssub.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vssubu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vssubu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vsub.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vsub.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vsuxei1024.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsuxei128.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsuxei16.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsuxei256.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsuxei32.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsuxei512.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsuxei64.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vsuxei8.v": ['nf', 'vm', 'vs2', 'rs1', 'vs3'],
        "vwadd.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vwadd.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vwadd.wv": ['vm', 'vs2', 'vs1', 'vd'],
        "vwadd.wx": ['vm', 'vs2', 'rs1', 'vd'],
        "vwaddu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vwaddu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vwaddu.wv": ['vm', 'vs2', 'vs1', 'vd'],
        "vwaddu.wx": ['vm', 'vs2', 'rs1', 'vd'],
        "vwmacc.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vwmacc.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vwmaccsu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vwmaccsu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vwmaccu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vwmaccu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vwmaccus.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vwmul.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vwmul.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vwmulsu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vwmulsu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vwmulu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vwmulu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vwredsum.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vwredsumu.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vwsub.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vwsub.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vwsub.wv": ['vm', 'vs2', 'vs1', 'vd'],
        "vwsub.wx": ['vm', 'vs2', 'rs1', 'vd'],
        "vwsubu.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vwsubu.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vwsubu.wv": ['vm', 'vs2', 'vs1', 'vd'],
        "vwsubu.wx": ['vm', 'vs2', 'rs1', 'vd'],
        "vxor.vi": ['vm', 'vs2', 'simm5', 'vd'],
        "vxor.vv": ['vm', 'vs2', 'vs1', 'vd'],
        "vxor.vx": ['vm', 'vs2', 'rs1', 'vd'],
        "vzext.vf2": ['vm', 'vs2', 'vd'],
        "vzext.vf4": ['vm', 'vs2', 'vd'],
        "vzext.vf8": ['vm', 'vs2', 'vd'],
    },
    "rv_v_aliases": {
        "vfredsum.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vfwredsum.vs": ['vm', 'vs2', 'vs1', 'vd'],
        "vl1r.v": ['rs1', 'vd'],
        "vl2r.v": ['rs1', 'vd'],
        "vl4r.v": ['rs1', 'vd'],
        "vl8r.v": ['rs1', 'vd'],
        "vle1.v": ['rs1', 'vd'],
        "vmandnot.mm": ['vm', 'vs2', 'vs1', 'vd'],
        "vmornot.mm": ['vm', 'vs2', 'vs1', 'vd'],
        "vpopc.m": ['vm', 'vs2', 'rd'],
        "vse1.v": ['rs1', 'vs3'],
    },
    "rv_zawrs": {
        "wrs.nto": [],
        "wrs.sto": [],
    },
    "rv_zbkx": {
        "xperm4": ['rd', 'rs1', 'rs2'],
        "xperm8": ['rd', 'rs1', 'rs2'],
    },
}
